name: API Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Execute API Tests
        run: ./gradlew apiTest  # Ganti dengan task yang sesuai untuk pengujian API

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-reports
          path: reports/api  # Ganti dengan path yang sesuai untuk laporan pengujian API